context:
  version: "0.11"

package:
  name: dfu-util
  version: ${{ version }}

build:
  number: 0

tests:
  - script:
      - if: unix
        then:
          - test -x "${PREFIX}/bin/dfu-util"
          - test -x "${PREFIX}/bin/dfu-prefix"
          - test -x "${PREFIX}/bin/dfu-suffix"
      - if: win
        then:
          - if not exist "%LIBRARY_BIN%\\dfu-util.exe" exit /b 1
          - if not exist "%LIBRARY_BIN%\\dfu-prefix.exe" exit /b 1
          - if not exist "%LIBRARY_BIN%\\dfu-suffix.exe" exit /b 1

about:
  homepage: https://dfu-util.sourceforge.net
  summary: Device Firmware Upgrade utilities
  license: GPL-2.0-or-later

extra:
  recipe-maintainers:
    - ionthedev
